package org.bread_experts_group.static_microserver

enum class DownloadFlag {
	DOWNLOAD,
	DISPLAY
}

val mimeMap = mapOf(
	"json" to ("application/json;charset=UTF-8" to DownloadFlag.DISPLAY),
	"jsonld" to ("application/ld+json;charset=UTF-8" to DownloadFlag.DISPLAY),
	"ogx" to ("application/ogg" to DownloadFlag.DOWNLOAD),
	"xml" to ("application/xml" to DownloadFlag.DISPLAY),
	"pom" to ("application/xml" to DownloadFlag.DISPLAY),
	"abw" to ("application/x-abiword" to DownloadFlag.DOWNLOAD),
	"arc" to ("application/x-freearc" to DownloadFlag.DOWNLOAD),
	"azw" to ("application/vnd.amazon.ebook" to DownloadFlag.DOWNLOAD),
	"bz" to ("application/x-bzip" to DownloadFlag.DOWNLOAD),
	"bz2" to ("application/x-bzip2" to DownloadFlag.DOWNLOAD),
	"cda" to ("application/x-cdf" to DownloadFlag.DOWNLOAD),
	"csh" to ("application/x-csh" to DownloadFlag.DOWNLOAD),
	"doc" to ("application/msword" to DownloadFlag.DOWNLOAD),
	"docx" to ("application/vnd.openxmlformats-officedocument.wordprocessingml.document" to DownloadFlag.DOWNLOAD),
	"eot" to ("application/vnd.ms-fontobject" to DownloadFlag.DOWNLOAD),
	"epub" to ("application/epub+zip" to DownloadFlag.DOWNLOAD),
	"gz" to ("application/gzip" to DownloadFlag.DOWNLOAD),
	"jar" to ("application/java-archive" to DownloadFlag.DOWNLOAD),
	"mpkg" to ("application/vnd.apple.installer+xml" to DownloadFlag.DOWNLOAD),
	"odp" to ("application/vnd.oasis.opendocument.presentation" to DownloadFlag.DOWNLOAD),
	"ods" to ("application/vnd.oasis.opendocument.spreadsheet" to DownloadFlag.DOWNLOAD),
	"odt" to ("application/vnd.oasis.opendocument.text" to DownloadFlag.DOWNLOAD),
	"pdf" to ("application/pdf" to DownloadFlag.DISPLAY),
	"php" to ("application/x-httpd-php" to DownloadFlag.DISPLAY),
	"ppt" to ("application/vnd.ms-powerpoint" to DownloadFlag.DOWNLOAD),
	"pptx" to ("application/vnd.openxmlformats-officedocument.presentationml.presentation" to DownloadFlag.DOWNLOAD),
	"rar" to ("application/vnd.rar" to DownloadFlag.DOWNLOAD),
	"rtf" to ("application/rtf" to DownloadFlag.DOWNLOAD),
	"sh" to ("application/x-sh" to DownloadFlag.DISPLAY),
	"bat" to ("application/x-bat;charset=UTF-8" to DownloadFlag.DISPLAY),
	"tar" to ("application/x-tar" to DownloadFlag.DOWNLOAD),
	"vsd" to ("application/vnd.visio" to DownloadFlag.DOWNLOAD),
	"xhtml" to ("application/xhtml+xml;charset=UTF-8" to DownloadFlag.DISPLAY),
	"xls" to ("application/vnd.ms-excel" to DownloadFlag.DOWNLOAD),
	"xlsx" to ("application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" to DownloadFlag.DOWNLOAD),
	"xul" to ("application/vnd.mozilla.xul+xml" to DownloadFlag.DOWNLOAD),
	"zip" to ("application/zip" to DownloadFlag.DOWNLOAD),
	"7z" to ("application/x-7z-compressed" to DownloadFlag.DOWNLOAD),
	"exe" to ("application/vnd.microsoft.portable-executable" to DownloadFlag.DOWNLOAD),
	"txt" to ("text/plain;charset=UTF-8" to DownloadFlag.DISPLAY),
	"md5" to ("text/plain;charset=UTF-8" to DownloadFlag.DISPLAY),
	"sha1" to ("text/plain;charset=UTF-8" to DownloadFlag.DISPLAY),
	"sha256" to ("text/plain;charset=UTF-8" to DownloadFlag.DISPLAY),
	"sha512" to ("text/plain;charset=UTF-8" to DownloadFlag.DISPLAY),
	"asc" to ("text/plain;charset=UTF-8" to DownloadFlag.DISPLAY),
	"begsm" to ("text/plain;charset=UTF-8" to DownloadFlag.DISPLAY),
	"kt" to ("text/plain;charset=UTF-8" to DownloadFlag.DISPLAY),
	"css" to ("text/css;charset=UTF-8" to DownloadFlag.DISPLAY),
	"csv" to ("text/csv;charset=UTF-8" to DownloadFlag.DISPLAY),
	"html" to ("text/html;charset=UTF-8" to DownloadFlag.DISPLAY),
	"java" to ("text/plain;charset=UTF-8" to DownloadFlag.DISPLAY),
	"kts" to ("text/plain;charset=UTF-8" to DownloadFlag.DISPLAY),
	"kt" to ("text/plain;charset=UTF-8" to DownloadFlag.DISPLAY),
	"gitignore" to ("text/plain;charset=UTF-8" to DownloadFlag.DISPLAY),
	"properties" to ("text/plain;charset=UTF-8" to DownloadFlag.DISPLAY),
	"js" to ("text/javascript;charset=UTF-8" to DownloadFlag.DISPLAY),
	"mjs" to ("text/javascript;charset=UTF-8" to DownloadFlag.DISPLAY),
	"ics" to ("text/calendar;charset=UTF-8" to DownloadFlag.DOWNLOAD),
	"ico" to ("image/x-icon" to DownloadFlag.DISPLAY),
	"png" to ("image/png" to DownloadFlag.DISPLAY),
	"apng" to ("image/apng" to DownloadFlag.DISPLAY),
	"jpg" to ("image/jpeg" to DownloadFlag.DISPLAY),
	"jpeg" to ("image/jpeg" to DownloadFlag.DISPLAY),
	"jpe" to ("image/jpeg" to DownloadFlag.DISPLAY),
	"jif" to ("image/jpeg" to DownloadFlag.DISPLAY),
	"jfif" to ("image/jpeg" to DownloadFlag.DISPLAY),
	"jfi" to ("image/jpeg" to DownloadFlag.DISPLAY),
	"gif" to ("image/gif" to DownloadFlag.DISPLAY),
	"avif" to ("image/avif" to DownloadFlag.DISPLAY),
	"svg" to ("image/svg+xml;charset=UTF-8" to DownloadFlag.DISPLAY),
	"svgz" to ("image/svg+xml;charset=UTF-8" to DownloadFlag.DISPLAY),
	"webp" to ("image/webp" to DownloadFlag.DISPLAY),
	"aac" to ("audio/aac" to DownloadFlag.DISPLAY),
	"mid" to ("audio/midi" to DownloadFlag.DISPLAY),
	"midi" to ("audio/midi" to DownloadFlag.DISPLAY),
	"mp3" to ("audio/mpeg" to DownloadFlag.DISPLAY),
	"wav" to ("audio/wav" to DownloadFlag.DISPLAY),
	"weba" to ("audio/webm" to DownloadFlag.DISPLAY),
	"flac" to ("audio/flac" to DownloadFlag.DISPLAY),
	"opus" to ("audio/ogg" to DownloadFlag.DISPLAY),
	"oga" to ("audio/ogg" to DownloadFlag.DISPLAY),
	"ogv" to ("video/ogg" to DownloadFlag.DISPLAY),
	"avi" to ("video/x-msvideo" to DownloadFlag.DISPLAY),
	"mp4" to ("video/mp4" to DownloadFlag.DISPLAY),
	"mpeg" to ("video/mpeg" to DownloadFlag.DISPLAY),
	"ts" to ("video/mp2t" to DownloadFlag.DISPLAY),
	"webm" to ("video/webm" to DownloadFlag.DISPLAY),
	"3gp" to ("video/3gpp" to DownloadFlag.DISPLAY),
	"3g2" to ("video/3gpp2" to DownloadFlag.DISPLAY),
)